// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeFJm31DB3s7Vl6ZwD910dewcDe3kRTgw',
    appId: '1:374258698014:web:af1bfa3462053629182b0f',
    messagingSenderId: '374258698014',
    projectId: 'app-ijin',
    authDomain: 'app-ijin.firebaseapp.com',
    storageBucket: 'app-ijin.firebasestorage.app',
    measurementId: 'G-EHT249T6PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpEHwsZaZR_jUYhTZ_whDRYqqb3ZSp3i4',
    appId: '1:374258698014:android:01c2f4325b178b22182b0f',
    messagingSenderId: '374258698014',
    projectId: 'app-ijin',
    storageBucket: 'app-ijin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL8fp_ETDj99tb3RDaridr29fcVnCNS0c',
    appId: '1:374258698014:ios:b199f7d87f55b491182b0f',
    messagingSenderId: '374258698014',
    projectId: 'app-ijin',
    storageBucket: 'app-ijin.firebasestorage.app',
    iosBundleId: 'com.example.appIjin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL8fp_ETDj99tb3RDaridr29fcVnCNS0c',
    appId: '1:374258698014:ios:b199f7d87f55b491182b0f',
    messagingSenderId: '374258698014',
    projectId: 'app-ijin',
    storageBucket: 'app-ijin.firebasestorage.app',
    iosBundleId: 'com.example.appIjin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeFJm31DB3s7Vl6ZwD910dewcDe3kRTgw',
    appId: '1:374258698014:web:04c4d5f2f3eec747182b0f',
    messagingSenderId: '374258698014',
    projectId: 'app-ijin',
    authDomain: 'app-ijin.firebaseapp.com',
    storageBucket: 'app-ijin.firebasestorage.app',
    measurementId: 'G-9X74LWEQXK',
  );
}
